# Docker Compose for Testing - exposes shutdown notification ports to host

services:
  # NFTables Game Server (with exposed shutdown ports for testing)
  nftables-server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: nftables-server-container
    privileged: true
    networks:
      - game-network
    ports:
      # Expose shutdown notification ports for host-based testing
      - "7778:7778/udp"
      - "7779:7779/udp"
      - "7780:7780/udp"
      - "7781:7781/udp"
      - "7782:7782/udp"
      - "7783:7783/udp"
      - "7784:7784/udp"
      - "7785:7785/udp"
      - "7786:7786/udp"
      - "7787:7787/udp"
    volumes:
      - ./configs/nftables/nftables.conf:/etc/nftables/nftables.conf:ro
      - ./results:/shared
    environment:
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1                # Force unbuffered output for real-time logging
      - SERVER_DURATION=${DURATION:-120}  # Use same duration as client by default
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: python3 -m src.server.nftables-test-server game ${SERVER_DURATION:-120}
    
  # Game Client Simulator
  game-client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: game-client-container
    depends_on:
      - nftables-server
    networks:
      - game-network
    volumes:
      - ./results:/shared
    environment:
      - TERM=xterm-256color
      - PYTHONUNBUFFERED=1                                # Force unbuffered output for real-time logging
      - NUM_CLIENTS=${NUM_CLIENTS:-18}                    # Number of simulated clients (default: 18)
      - SERVER_IP=nftables-server-container               # Target server hostname
      - DURATION=${DURATION:-120}                         # Simulation duration in seconds (default: 120)
      - CONNECTIONS_PER_PLAYER=${CONNECTIONS_PER_PLAYER:-3} # Concurrent connections per player (default: 3)
      # Authentic UT Server Network Specifications
      - UT_UDP_OVERHEAD=${UT_UDP_OVERHEAD:-28}            # UT protocol UDP overhead (bytes)
      - UT_TICKRATE=${UT_TICKRATE:-85}                    # Server tickrate (Hz)
      - UT_DEFAULT_NETSPEED=${UT_DEFAULT_NETSPEED:-40000} # Default netspeed (bytes/sec)
      - UT_MAX_NETSPEED=${UT_MAX_NETSPEED:-100000}        # Maximum netspeed (bytes/sec)
    command: >
      sh -c "sleep 5 && python3 -m src.client.game-client-simulator"

networks:
  game-network:
    driver: bridge