# Docker Compose for Game Server + Client Simulation

services:
  # NFTables Game Server
  nftables-server:
    build:
      context: .
      dockerfile: src/server/Dockerfile
    container_name: nftables-server-container
    privileged: true
    networks:
      - game-network
    volumes:
      - ./configs/nftables/nftables.conf:/etc/nftables/nftables.conf:ro
      - ./results:/shared
    environment:
      - TERM=xterm-256color
      - SERVER_DURATION=${DURATION:-120}  # Use same duration as client by default
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    command: python3 -m src.server.nftables-test-server game ${SERVER_DURATION:-120}
    
  # Game Client Simulator
  game-client:
    build:
      context: .
      dockerfile: src/client/Dockerfile
    container_name: game-client-container
    depends_on:
      - nftables-server
    networks:
      - game-network
    volumes:
      - ./results:/shared
    environment:
      - TERM=xterm-256color
      - NUM_CLIENTS=${NUM_CLIENTS:-18}                    # Number of simulated clients (default: 18)
      - SERVER_IP=nftables-server-container               # Target server hostname
      - DURATION=${DURATION:-120}                         # Simulation duration in seconds (default: 120)
      - CONNECTIONS_PER_PLAYER=${CONNECTIONS_PER_PLAYER:-3} # Concurrent connections per player (default: 3)
      # Authentic UT Server Network Specifications
      - UT_UDP_OVERHEAD=${UT_UDP_OVERHEAD:-28}            # UT protocol UDP overhead (bytes)
      - UT_TICKRATE=${UT_TICKRATE:-85}                    # Server tickrate (Hz)
      - UT_DEFAULT_NETSPEED=${UT_DEFAULT_NETSPEED:-40000} # Default netspeed (bytes/sec)
      - UT_MAX_NETSPEED=${UT_MAX_NETSPEED:-100000}        # Maximum netspeed (bytes/sec)
    command: >
      sh -c "sleep 5 && python3 -m src.client.game-client-simulator"
  
  # Streamlit Dashboard
  dashboard:
    build:
      context: .
      dockerfile: src/dashboard/Dockerfile
    container_name: tus-dashboard-container
    depends_on:
      - nftables-server
      - game-client
    networks:
      - game-network
    ports:
      - "8501:8501"  # Streamlit dashboard port
    volumes:
      - ./results:/app/results:ro  # Read-only access to results
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  game-network:
    driver: bridge