services:
  nftables-test:
    build:
      context: ../..
      dockerfile: configs/docker/Dockerfile.server
    container_name: nftables-test-container
    privileged: true
    network_mode: host
    volumes:
      - ../nftables/nftables.conf:/etc/nftables/nftables.conf:ro
      - ../../src/utils/test-nftables.sh:/usr/local/bin/test-nftables.sh:ro
      - ../../src/utils/enhanced-test.sh:/usr/local/bin/enhanced-test.sh:ro
      - ../../src/server/nftables-test-server.py:/usr/local/bin/nftables-test-server.py:ro
      - ../../scripts/linux/run-auto-tests.sh:/usr/local/bin/run-auto-tests.sh:ro
      - ../../results:/shared
    environment:
      - TERM=xterm-256color
      - KEEP_RUNNING=false
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
  
  # Streamlit Dashboard
  dashboard:
    build:
      context: ../..
      dockerfile: configs/docker/Dockerfile.dashboard
    container_name: tus-dashboard-basic
    depends_on:
      - nftables-test
    ports:
      - "8501:8501"  # Streamlit dashboard port
    volumes:
      - ../results:/app/results:ro  # Read-only access to results
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s